#ifndef TYPES_HPP
#define TYPES_HPP

#include <string>
#include <vector>
#include "../Client/Client.hpp"

enum PARSE_ERR {
  NO_ERR = 0,
  SYNTHAX = 100,
  EMPTY_CMD = 300,
  ERR_NOSUCHNICK = 401,
  ERR_NOSUCHCHANNEL = 403,
  ERR_CANNOTSENDTOCHAN = 404,
  ERR_INVALIDCAPCMD = 410,
  ERR_NORECIPIENT = 411,
  ERR_NOTEXTTOSEND = 412,
  ERR_INPUTTOOLONG = 417,
  ERR_UNKNOWNCOMMAND = 421,
  ERR_NONICKNAMEGIVEN = 431,
  ERR_ERRONEUSNICKNAME = 432,
  ERR_NICKNAMEINUSE = 433,
  ERR_NICKCOLLISION = 436,
  ERR_USERNOTINCHANNEL = 441,
  ERR_NOTONCHANNEL = 442,
  ERR_USERONCHANNEL = 443,
  ERR_NOTREGISTERED = 451,
  ERR_NEEDMOREPARAMS = 461,
  ERR_ALREADYREGISTERED = 462,
  ERR_PASSWDMISMATCH = 464,
  ERR_CHANNELISFULL = 471,
  ERR_INVITEONLYCHAN = 473,
  ERR_BADCHANNELKEY = 475,
  ERR_NOPRIVILEGES = 481,
  ERR_CHANOPRIVSNEEDED = 482,
};

enum RPL_MSG {
  RPL_NONE = 000,
  RPL_WELCOME = 001,
  RPL_YOURHOST = 002,
  RPL_CREATED = 003,
  RPL_INTERN_SETNICK = 101,
  RPL_INTERN_CHANGENICK = 102,
  RPL_INTERN_SETUSER = 103,
  RPL_CHANNELMODEIS = 324,
  RPL_CREATIONTIME = 329,
  RPL_NOTOPIC = 331,
  RPL_TOPIC = 332,
  RPL_TOPICWHOTIME = 333,
  RPL_INVITING = 341,
  RPL_NAMREPLY = 353,
  RPL_ENDOFNAMES = 366,
  RPL_YOUREOPER = 381,
};

struct cmd_obj {
  PARSE_ERR error;
  std::vector<std::string> tags;
  std::string prefix;
  std::string command;
  Client* client;
  std::vector<std::string> parameters;
};

#endif  //TYPES_HPP
